/* scripts/migrate/GenerateMaterialsSeed.js — Sprint AI-126B Part 2 v1.1,
   Task 2 (Material Migration).

   Generates supabase/seed/0002_materials.sql — real, git-committed,
   idempotent DML (never a migration/schema/RLS/FK change, per this
   round's explicit "不得修改 Migration/Schema/RLS/FK" restriction) —
   from the platform's own already-real, already-shipped teaching
   material content:
     - Package track: js/data/TeachingMaterialData.js (generated by
       docs/TeachingMaterials/scripts/GenerateTeachingMaterialData.js
       from docs/TeachingMaterials/materials/tm_1..4/ — real exam
       transcriptions, not Mock Data).
     - Repository track: data/materials/MaterialRepositoryIndex.js +
       CivicsG10Ch5to6Exam20260730.js (real, human-analyzed exam
       transcript subset, honestly partial per that file's own
       disclosure — 6 of 50 source questions, the rest intentionally
       not fabricated).

   Loaded the same way tests/supabase/CrossDeviceSmoke.js already loads
   window.AHS files into plain Node (global.window = global; require()).
   This script makes NO network call and writes only a local .sql file —
   applying it to the real Supabase project is a separate, explicit step
   (supabase db query --linked --file, same mechanism already used for
   supabase/seed/0001_subjects.sql in .github/workflows/supabase-deploy.yml),
   run under elevated Management API access because materials/
   question_sets/questions are Admin Only writes per RLS (no mock
   client-side account has is_admin=true — see AuthRepository.js's own
   header for why this Sprint deliberately does not attempt to fabricate
   or self-escalate admin rights).

   Idempotency (judgment call, required for correctness, not spelled out
   by the Sprint — same discipline as 0001_subjects.sql): materials has
   a real `origin_key` unique constraint (AI-126A's own migration
   comment: "kept unique so a re-import is idempotent, matching
   TeachingMaterialLoader.js's own existing idMap behavior exactly") —
   used for `on conflict (origin_key) do update`. question_sets/questions
   have no natural unique key of their own (by design — see AI-126A's
   migration comments), so each INSERT here is instead guarded by a
   `where not exists (...)` matching on the real business key this
   script already knows (material_id/source for question_sets;
   question_set_id/"index" for questions) — re-running this generator
   and re-applying its output never duplicates a row, without touching
   Schema. */
"use strict";
const fs = require("fs");
const path = require("path");
const REPO = path.join(__dirname, "..", "..");

global.window = global;
require(path.join(REPO, "js/data/TeachingMaterialData.js"));
require(path.join(REPO, "data/materials/MaterialRepositoryIndex.js"));
require(path.join(REPO, "data/materials/CivicsG10Ch5to6Exam20260730.js"));
const AHS = global.AHS;

/* Same code/name pairs as supabase/seed/0001_subjects.sql — not a second,
   independently-invented mapping. Package track material.subject is a
   Chinese display name (js/runtime/TeachingMaterialLoader.js's own
   subjectKeyFromChineseName() reverses the identical AHS.Subjects table
   for the same reason); Repository track metadata.subject is already a
   real code (e.g. "civics" — that track's own existing convention, per
   TeachingMaterialLoader.js's repoMaterialPartial() comment). */
const SUBJECT_CODE_BY_NAME = {
  "國文": "chinese", "英文": "english", "數學": "math", "物理": "physics",
  "化學": "chemistry", "生物": "biology", "歷史": "history", "地理": "geography", "公民": "civics"
};
const KNOWN_SUBJECT_CODES = Object.keys(SUBJECT_CODE_BY_NAME).map(function (k) { return SUBJECT_CODE_BY_NAME[k]; });
const OPTION_KEYS = ["A", "B", "C", "D", "E", "F"];

function sqlStr(v) {
  if (v === null || v === undefined || v === "") { return v === "" ? "''" : "NULL"; }
  return "'" + String(v).replace(/'/g, "''") + "'";
}
function sqlJson(v) {
  return "'" + JSON.stringify(v).replace(/'/g, "''") + "'::jsonb";
}
function mapDifficulty(cn) {
  if (!cn) { return "medium"; }
  if (cn.indexOf("困難") !== -1) { return "hard"; }
  if (cn.indexOf("簡單") !== -1) { return "easy"; }
  return "medium";
}

const lines = [];
let materialCount = 0;
let questionCount = 0;
let skipped = [];

function emitMaterial(originKey, subjectCode, title, chapter, grade, category, sourceTrack) {
  materialCount += 1;
  lines.push(
    "insert into public.materials (origin_key, subject_id, title, chapter, grade, category, source_track)\n" +
    "select " + sqlStr(originKey) + ", s.id, " + sqlStr(title) + ", " + sqlStr(chapter) + ", " + sqlStr(grade) + ", " + sqlStr(category) + ", " + sqlStr(sourceTrack) + "\n" +
    "from public.subjects s where s.code = " + sqlStr(subjectCode) + "\n" +
    "on conflict (origin_key) do update set\n" +
    "  subject_id = excluded.subject_id, title = excluded.title, chapter = excluded.chapter,\n" +
    "  grade = excluded.grade, category = excluded.category, source_track = excluded.source_track;"
  );
  lines.push(
    "insert into public.question_sets (material_id, subject_id, source, title)\n" +
    "select m.id, m.subject_id, 'ORIGINAL', m.title from public.materials m where m.origin_key = " + sqlStr(originKey) + "\n" +
    "  and not exists (select 1 from public.question_sets qs where qs.material_id = m.id and qs.source = 'ORIGINAL');"
  );
}

function emitQuestion(originKey, index, text, options, correctAnswer, explanation, knowledgePoint, difficulty) {
  questionCount += 1;
  lines.push(
    "insert into public.questions (question_set_id, \"index\", text, question_type, options, correct_answer, explanation, knowledge_point, difficulty)\n" +
    "select qs.id, " + index + ", " + sqlStr(text) + ", 'single_choice', " + sqlJson(options) + ", " + sqlStr(correctAnswer) + ", " + sqlStr(explanation) + ", " + sqlStr(knowledgePoint) + ", " + sqlStr(difficulty) + "\n" +
    "from public.question_sets qs join public.materials m on m.id = qs.material_id\n" +
    "where m.origin_key = " + sqlStr(originKey) + " and qs.source = 'ORIGINAL'\n" +
    "  and not exists (select 1 from public.questions q where q.question_set_id = qs.id and q.\"index\" = " + index + ");"
  );
}

/* --- Package track (tm_1..4) --- */
(Array.isArray(AHS.TeachingMaterialData) ? AHS.TeachingMaterialData : []).forEach(function (entry) {
  const originKey = entry.materialId;
  const mat = entry.material || {};
  const subjectCode = SUBJECT_CODE_BY_NAME[mat.subject];
  if (!subjectCode) { skipped.push(originKey + " (unmapped subject " + mat.subject + ")"); return; }
  lines.push("-- Package track: " + originKey + " (" + mat.subject + ")");
  emitMaterial(originKey, subjectCode, mat.title, mat.chapter, mat.grade, mat.category, "PACKAGE");
  var idx = 0;
  (entry.questions || []).forEach(function (q) {
    /* Only single_choice, only when the real answer resolves to one of
       the real options — same honest filter
       TeachingMaterialLoader.buildExamCompatibleQuestions() already
       applies client-side; a question that doesn't qualify is left out
       of the Repository migration too, never fabricated into a fake
       multiple-choice shape. */
    if (!q || q.type !== "single_choice" || !Array.isArray(q.options)) { return; }
    var answerIndex = q.options.indexOf(q.answer);
    if (answerIndex === -1 || answerIndex >= OPTION_KEYS.length) { return; }
    idx += 1;
    var options = q.options.map(function (text, i) { return { key: OPTION_KEYS[i] || String(i), text: text }; });
    var correctAnswer = OPTION_KEYS[answerIndex];
    emitQuestion(originKey, idx, q.question, options, correctAnswer, q.explanation || "", q.knowledgePoint || mat.chapter || "", "medium");
  });
  lines.push("");
});

/* --- Repository track (civics-g10-ch5-6-exam-20260730, ...) --- */
(AHS.MaterialRepository && typeof AHS.MaterialRepository.list === "function" ? AHS.MaterialRepository.list() : []).forEach(function (record) {
  const originKey = record.id;
  const meta = record.metadata || {};
  const summary = record.summary || {};
  const subjectCode = meta.subject;
  if (!subjectCode || KNOWN_SUBJECT_CODES.indexOf(subjectCode) === -1) { skipped.push(originKey + " (unmapped subject " + subjectCode + ")"); return; }
  lines.push("-- Repository track: " + originKey + " (" + subjectCode + ")");
  emitMaterial(originKey, subjectCode, summary.title || meta.chapter || originKey, meta.chapter || "", meta.grade || "", meta.unit || "", "REPOSITORY");
  var bank = record.questionBank || {};
  var singleChoice = Array.isArray(bank.singleChoice) ? bank.singleChoice : [];
  var idx = 0;
  singleChoice.forEach(function (q) {
    if (!q || !Array.isArray(q.options) || !q.options.length || !q.correctAnswer) { return; }
    idx += 1;
    emitQuestion(originKey, idx, q.text, q.options, q.correctAnswer, q.explanation || "", q.knowledgePoint || meta.chapter || "", mapDifficulty(q.difficulty));
  });
  lines.push("");
});

const header = [
  "-- 0002_materials.sql — AI-126B Part 2 v1.1, Task 2 (Material Migration).",
  "--",
  "-- GENERATED FILE — do not hand-edit. Produced by",
  "-- scripts/migrate/GenerateMaterialsSeed.js from the platform's own real,",
  "-- already-shipped teaching material content (js/data/TeachingMaterialData.js",
  "-- Package track + data/materials/*.js Repository track) — never Mock Data,",
  "-- never fabricated. Re-run the generator (and commit the result) after any",
  "-- change to those source files.",
  "--",
  "-- Pure DML (insert/on-conflict/where-not-exists only) — no schema,",
  "-- migration, RLS, or FK change, per this round's explicit restriction.",
  "-- Idempotent: materials upserts by its own real `origin_key` unique",
  "-- constraint; question_sets/questions (no natural unique key by design,",
  "-- see supabase/migrations/20260807000003_content_tables.sql's own",
  "-- comments) are each guarded by a real `where not exists` business-key",
  "-- check instead, so re-applying this file never duplicates a row.",
  "--",
  "-- Not applied automatically by `supabase db push` (that only runs",
  "-- migrations/, same as 0001_subjects.sql). Requires elevated",
  "-- Management API / --linked access, since materials/question_sets/",
  "-- questions are Admin Only writes per RLS (20260807000005_rls_policies.sql)",
  "-- and no mock client-side account holds is_admin — apply via:",
  "--   supabase db query --linked --file supabase/seed/0002_materials.sql",
  "--",
  "-- Generated " + new Date().toISOString() + " — " + materialCount + " materials, " + questionCount + " questions." +
    (skipped.length ? " Skipped (unmapped subject, not fabricated): " + skipped.join(", ") + "." : ""),
  ""
];

fs.writeFileSync(path.join(REPO, "supabase/seed/0002_materials.sql"), header.join("\n") + lines.join("\n") + "\n");
console.log("Wrote supabase/seed/0002_materials.sql — " + materialCount + " materials, " + questionCount + " questions.");
if (skipped.length) { console.log("Skipped: " + skipped.join(", ")); }
